config/routes.rb
BestFacts::Application.routes.draw do  

  root "facts#index"

  scope :format => true, :constraints => { :format => 'json' } do
    resources :facts, :constraints => {:format => /json/}
  end

  scope :format => true, :constraints => { :format => 'json' } do
    post "user/register", constraints: {format: 'json'}
    post "user/login", constraints: {format: 'json'}
  end

  get "user/logout"

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  belongs_to :author
  belongs_to :user

  validates :content, :title, presence:true
  validates :user, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :facts
  
  has_secure_password

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :app_constants
  before_filter :redirect_if_no_user_session

  private

    def app_constants
      @current_user = session[:USER]
      gon.userLoggedIn = is_user_logged_in?
      gon.username = current_user_name
      gon.userid = current_user_id
    end

    def redirect_if_no_user_session
      unless(@current_user.blank? or @current_user[:id].blank?)
        return;
      end

      render :json => { alert: 'You should login to continue', redirect: root_url}, :status => 401
    end

  protected
    def current_user_name
      return @current_user[:name] if is_user_logged_in?
    end
    
    def current_user_id
      return @current_user[:id] if is_user_logged_in?
    end

    def is_user_logged_in?
      return !(@current_user.blank? or @current_user[:id].blank?)
    end

    def load_user_to_session(session,user)
      session[:USER] = {
        id:user.id,
        name:user.name,
        email:user.email
      }
    end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController

  before_action :set_fact, only: [:show, :edit, :update, :destroy]
  skip_before_filter :redirect_if_no_user_session, :only=>[:index]

  # GET /facts
  # GET /facts.json
  def index
    if(params[:sort].blank? || params[:sort] == 'Author')
      sort_order = "users.name";
    elsif(params[:sort] == 'Title')
      sort_order = "facts.title";
    elsif(params[:sort] == 'Content')
      sort_order = "facts.content";
    end
    @facts = Fact.where("is_active = true").includes(:user).order(sort_order).load
  end

  # GET /facts/1
  # GET /facts/1.json
  def show
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
  end

  # POST /facts.json
  def create
    @fact = Fact.new(title: params[:title], content: params[:content], is_active: true, user_id: current_user_id)

    if @fact.save!
      render json: {id:@fact.id, title:@fact.title, content:@fact.content, username: @fact.user.name, user_id:@fact.user.id}, status: :created
    else
      render json: @fact.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /facts/1
  # PATCH/PUT /facts/1.json
  def update
    @updatedCount = Fact.where(["user_id = ? and id = ?", current_user_id, params[:id]]).update_all(["content = ?, title=?, updated_at = ?",params[:content], params[:title], Time.now.utc])

    if(@updatedCount == 1)
      head :no_content
    else
      render json: {}, status: 401
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @updatedCount = Fact.where(["user_id = ? and id = ?", current_user_id, params[:id]]).update_all(["is_active = ?, updated_at = ?",false, Time.now.utc])

    if(@updatedCount == 1)
      head :no_content
    else
      render json: {}, status: 401
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fact_params
      params[:fact]
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_filter :redirect_if_no_user_session, :only => [:signout, :register, :login]
  def register
    user = User.new(name: params[:name], email: params[:email], password: params[:password], password_confirmation: params[:cpassword])

    if(user.save)
      reset_session
      load_user_to_session(session,user)

      render json: {}, status: :created
    else
      render json: user.errors, status: :unprocessable_entity
    end
  end

  def login
    user = User.find_by("email = ?", params[:email]).try(:authenticate, params[:password])
    if(!user.blank?)
      reset_session
      load_user_to_session(session,user)

      render json: {}
    else
      render json: {}, status: 401
    end
  end

  def logout
    session.delete(:USER)
    reset_session
    @current_user = nil

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/facts/_form.html.erb
<%= form_for(@fact) do |f| %>
  <% if @fact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
      <% @fact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title%>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facts/edit.html.erb
<h1>Editing fact</h1>

<%= render 'form' %>

<%= link_to 'Show', @fact %> |
<%= link_to 'Back', facts_path %>

app/views/facts/index.html.erb
<div class="jumbotron">
  <h1>Best Facts app!</h1>
  <p>Single place to get facts right</p>
</div>

<div class="panel panel-default" ng-controller="FactController">
  <!-- Default panel contents -->
  <div class="panel-heading" ng-cloak>
    <span>Listing all facts!!</span>
    <!-- <a class="btn pull-right" ng-class="{show: isUserLoggedIn, hide:!isUserLoggedIn}"><i class="fa fa-plus"></i> Add new fact</a> -->
    <a data-toggle="modal" data-target="#loginModal" class="btn pull-right" ng-class="{show: !isUserLoggedIn, hide:isUserLoggedIn}"><i class="fa fa-sign-in"></i> Login/Register to add a fact!</a>
  </div>
  <div class="panel-body fact-list-heading">
    <div class="col-md-1"># </div>
    <div class="col-md-2"> <span class="fact-title" ng-click="getAllFacts('Author')"> Author </span></div>
    <div class="col-md-4"> <span class="fact-title" ng-click="getAllFacts('Title')"> Title </span></div>
    <div class="col-md-4"> <span class="fact-title" ng-click="getAllFacts('Content')"> Content </span></div>
    <div class="col-md-1"></div>
  </div>
  <ul class="list-group" ng-cloak>
    <li class="list-group-item single-fact" ng-repeat="fact in facts">
      <div class="row">
        <div class="col-md-1">{{$index + 1}}</div>
        <div class="col-md-2">{{fact.username}}</div>
        <div class="col-md-4">
          <span ng-hide="fact.editing">{{fact.title}}</span>
          <input ng-show="fact.editing" class="form-control" type="text" ng-init="fact.newTitle = fact.title" ng-model="fact.newTitle" required/>
        </div>
        <div class="col-md-4">
          <span ng-hide="fact.editing">{{fact.content}}</span>
          <textarea ng-show="fact.editing" class="form-control auto-grow" ng-model="fact.newContent" ng-init="fact.newContent=fact.content"></textarea>
        </div>
        <div class="col-md-1 fact-edit-control" ng-show="fact.user_id === current_user_id">
          <i class="fa fa-trash-o pull-right" ng-click="removeFact(fact)" ng-hide="fact.editing"></i>
          <i class="fa fa-pencil pull-right" ng-click="fact.editing=true" ng-hide="fact.editing"></i>

          <i class="fa fa-times pull-right" ng-click="fact.editing=false" ng-show="fact.editing"></i>
          <i class="fa fa-check pull-right" ng-click="updateFact(fact)" ng-show="fact.editing"></i>
        </div>
      </div>
    </li>
    <li class="list-group-item new-fact">
      <div class="row">
        <div class="col-md-1">{{facts.length + 1}}</div>
        <div class="col-md-2">{{loggedinUsername}}</div>
        <div class="col-md-4">
          <input ng-show="addingFact" class="form-control" type="text" ng-model="newTitle" required/>
        </div>
        <div class="col-md-4">
          <textarea ng-show="addingFact" rows="1" class="form-control auto-grow" ng-model="newContent" required></textarea>
        </div>
        <div class="col-md-1">
          <i ng-click="addingFact=false" class="fa fa-times pull-right"></i>
          <i ng-click="createFact()" class="fa fa-check pull-right"></i>
        </div>
      </div>
      <div class="add-new-fact" ng-init="addingFact=false" ng-hide="addingFact">
        <a ng-click="addingFact=true" ng-show="isUserLoggedIn" class="btn">Click to add a new fact!!</a>
        <a data-toggle="modal" ng-hide="isUserLoggedIn" data-target="#loginModal" class="btn" ng-class="{show: !isUserLoggedIn, hide:isUserLoggedIn}"><i class="fa fa-sign-in"></i> Login/Register to add a fact!</a>
      </div>
    </li>
  </ul>
</div>

app/views/facts/new.html.erb
<h1>New fact</h1>

<%= render 'form' %>

<%= link_to 'Back', facts_path %>

app/views/facts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fact_path(@fact) %> |
<%= link_to 'Back', facts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8 ]>    <html id="ng-app" ng-app="bestfacts" class="ie"> <![endif]-->
<!--[if IE 9 ]>    <html id="ng-app" ng-app="bestfacts" class="ie"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html id="ng-app" ng-app="bestfacts" class=""> <!--<![endif]-->
<head>
  <title>BestFacts</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= csrf_meta_tags %>
  <%= include_gon %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.3/angular.js" %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation" ng-controller="NavbarController">
  <div class="container"><div class="row">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Best Facts</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <% if @current_user.blank? %>
        <form name="loginForm" ng-submit="authenticateUser()" class="navbar-form navbar-right hide" role="search" ng-class="{show:!hideForm, hide:hideForm}">
          <div class="form-group">
            <label class="sr-only" for="exampleInputEmail2">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email" ng-model="email" required>
          </div>
          <div class="form-group">
            <label class="sr-only" for="exampleInputPassword2">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" ng-model="password" required>
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
          <button ng-click="loginClicked()" type="button" class="btn close" aria-hidden="true">&times;</button>
        </form>
      <% end %>

      <% if @current_user.blank? %>
        <ul ng-hide="isUserLoggedIn" class="nav navbar-nav navbar-right">
          <li><a eat-click="true" data-toggle="modal" data-target="#loginModal" href="#">Register</a></li>
          <li><a ng-class="{show:hideForm, hide:!hideForm}" ng-click="loginClicked()" eat-click="true" href="#">Login</a> </li>
        </ul>
      <% end %>

      <% unless @current_user.blank? %>
        <ul ng-show="isUserLoggedIn" class="nav navbar-nav navbar-right">
          <li><a eat-click="true" href="#">{{username}}</a></li>
          <li><a href="/user/logout"><i class="fa fa-sign-out"></i></a></li>
        </ul>
      <% end %>

    </div>
  </div></div>
  </nav>

  <div class="container">
    <div class="row">
<%= yield %>
    </div>
  </div>

  <%= render "user/login_modal" %>

  <%= javascript_include_tag "application"%>
</body>
</html>

app/views/user/_login_modal.html.erb
<div class="modal fade loginModal" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true" ng-controller="RegistrationController">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="loginModalLabel">Register with Best Facts</h4>
      </div>
      <div class="modal-body">
        <form name="loginForm" class="form-horizontal" role="form">
            <div class="form-group">
              <label for="inputName" class="col-sm-2 control-label">Name</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="inputName" placeholder="Your name" ng-model="fullName" name="fullName" required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputEmail" class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail" placeholder="Email" ng-model="email" name="email" required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword" class="col-sm-2 control-label">Password</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword" placeholder="Password" ng-model="passwd" name="passwd" equals="cpasswd" required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputConfirmPassword" class="col-sm-2 control-label">Confirm Password</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" id="inputConfirmPassword" placeholder="Confirm Password" ng-model="cpasswd" name="cpasswd" equals="passwd" required>
              </div>
            </div>
          </form>
      </div>
      <div class="modal-footer">
        <a type="button" class="btn" data-dismiss="modal">Close</a>
        <button ng-disabled="loginForm.$invalid" ng-click="registerUser()" type="button" class="btn btn-primary">Register</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/user/login.html.erb
<h1>User#login</h1>
<p>Find me in app/views/user/login.html.erb</p>

app/views/user/register.html.erb
<h1>User#register</h1>
<p>Find me in app/views/user/register.html.erb</p>